dist: trusty
os: linux
language: cpp
compiler: g++
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake
      - boost1.74
      - python3-dev
script:
  - export CXX=g++-7
  - cd methodDevelopment
  - mkdir build
  - cd build
  - cmake -D TEST:BOOL=TRUE -D ENABLE_COVERAGE:BOOL=TRUE ..
  - make
  - ./tester
after_success:
  - rm -rf CMakeFiles/tester.dir/tests
  - bash <(curl -s https://codecov.io/bash)