name: ubuntu-cmake-compile

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running Cmake
      run: cmake .
    - name: Running make
      run: make
