name: ubuntu-cmake-compile

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing Boost and python3-dev
      run: sudo apt-get update && sudo apt-get install libboost-all-dev python3-dev
    - name: Running Cmake
      run: cmake ./methodDevelopment
    - name: Running make
      run: make
